### ISSUE TITLE
Dependencie issue with Nokogiri gem

### ISSUE THREAD

**Issue by Younnah** [jasonjoh/o365-tutorial#18]
Hi!

I have a dependencie issue between nokogiri and microsoft_graph gems...

Here are the versions that I use:
ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin19]
ruby on rails : 5.2.3

<img width="537" alt="Screenshot 2020-02-10 at 18 01 03" src="https://user-images.githubusercontent.com/26743683/74172024-d04b6f80-4c2f-11ea-84f2-8d2d51606b0a.png">

Will there be a fix planned?
For now, I am using the ruby_outlook gem to work around this problem.

Thank you for your answer !

**Comment by jasonjoh** [comment]
It appears they have merged in a fix: https://github.com/microsoftgraph/msgraph-sdk-ruby/pull/45

Hope that helps!
