### ISSUE TITLE
Error will come while fetching messages

### ISSUE THREAD

**Issue by aliabbas-2012** [jasonjoh/o365-tutorial#4]
"{\"error\":{\"code\":\"ErrorMissingEmailAddress\",\"message\":\"When making a request as an account that does not have a mailbox, you must specify the mailbox primary SMTP address for any distinguished folder Ids.\"}}"

**Comment by jasonjoh** [comment]
This error indicates that your email account hasn't been enabled for the REST API. See http://stackoverflow.com/questions/34482838/errormissingemailaddress-error-in-outlook-rest-api.
