### ISSUE TITLE
Response token doesn't contain a preferred_username claim

### ISSUE THREAD

**Issue by johnmckay-reward** [jasonjoh/o365-tutorial#6]
Thanks for this tutorial, I am having an issue where the response token doesn't contain the _preferred_username_ claim referred to, an example of what I do get back is below:

```
{  
   "ver":"2.0",
   "iss":"https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0",
   "aud":"0ab6433e-84fc-469b-8c72-41f7a0241a61",
   "exp":1458142389,
   "iat":1458055989,
   "at_hash":"0OYaLKpTTdHNBrQNOqwQ0Q",
   "sub":"AAAAAAAAAAAAAAAAAAAAAC1TrOaOmvInYrFAyrQjlFI",
   "tid":"9188040d-6c67-4c5b-b112-36a304b66dad"
}
```

The above is the value of _decoded_token_ in the _get_email_from_id_token_ function, no username.

Is the tutorial out of date, or am I doing something wrong?

Thanks

**Comment by ghost** [comment]
I am also having this issue :0

**Comment by jasonjoh** [comment]
The Azure team deployed a [breaking change to their v2 auth endpoint](https://blogs.technet.microsoft.com/b/ad/archive/2016/01/27/for-developers-important-upcoming-changes-to-the-v2-0-auth-protocol.aspx), which is causing the `preferred_username` to not be present. You need to add `profile` to the `SCOPES` array in `auth_helper.rb`. I'll post an update to the tutorial after the Build conference.

**Comment by johnmckay-reward** [comment]
@jasonjoh Thanks very much!

I have asked on StackOverflow too, so feel free to answer if you wish.

http://stackoverflow.com/q/36015959/969613

**Comment by ghost** [comment]
Working now thanks guys for the help :)

**Comment by ghost** [comment]
Actual scope added for anyone's reference... 

SCOPES = [ 'openid', 'https://outlook.office.com/mail.read', 'profile' ]

**Comment by jasonjoh** [comment]
I've removed the code that parses the ID token altogether, so you no longer need to include the `profile` scope. Now the app makes an API call to the `/api/v2.0/Me` endpoint to get the user's email address. This is a more reliable method, as the `preferred_username` can be in a format other than SMTP email address.
